name: vortasks
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  mobx_codegen: ^2.6.1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  uuid: ^4.4.0
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  mockito: ^5.4.4

flutter:

  uses-material-design: true

  assets:
    - assets/icons/app/
    - assets/icons/splash/
  
flutter_native_splash:
  android: true
  ios: true
  image: "assets/icons/splash/ic_splash.png"
  image_dark: "assets/icons/splash/ic_splash.png"
  color: "#02183f"
  color_dark: "#050033"
  android_12:
    image: "assets/icons/splash/ic_splash_android_12.png"
    icon_background_color: "#02183f"
    image_dark: "assets/icons/splash/ic_splash_android_12.png"
    icon_background_color_dark: "#050033"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app/ic_launcher.png"
  adaptive_icon_background: "#02183f"
  adaptive_icon_foreground: "assets/icons/app/ic_launcher.png"
  